### ISSUE TITLE
Weird problems with polylang pro and sync when plugin active

### ISSUE THREAD

**Issue by timiwahalahti** [aucor/polylang-smart-language-select-disabler#3]
For some very odd reason, looks like this plugin causes problem with post/page synchronization setting when using polylang pro. Pages keep being set to synchronized event after disabling the sync.

I will give a better look for this when there's a bit more time on my hands.

**Comment by TeemuSuoranta** [comment]
It's that same old html attribute disabled that gives all kinds of weird troubles. I should replace it with hiding the select with CSS and add the current language with p tag.

**Comment by TeemuSuoranta** [comment]
I have now rewritten the select logic as I should have some time ago. Can you update to the newest version (1.0.1) and confirm that this was fixed?

**Comment by timiwahalahti** [comment]
Fixed long time ago. Closing the issue.
