### ISSUE TITLE
Maybe disable default lang select?

### ISSUE THREAD

**Issue by timiwahalahti** [aucor/polylang-smart-language-select-disabler#6]
Could and should this plugin be extended to disable changing the default language? It can cause the same kind of problems as changing the post/term language.

**Comment by TeemuSuoranta** [comment]
Makes sense to me. Do you have ideas how to do it? Is a bit of CSS enough?

**Comment by timiwahalahti** [comment]
No idea at the moment, but can make a PR soon _(ish)_ since you agree this feature makes sense.

**Comment by timiwahalahti** [comment]
PR in #7, moving the discussion to there.
